index:
    path: /
    controller: App\Controller\ApiController::index
vessel_track_list:
    path: /vessel_track/list
    defaults: { _controller: App\Controller\ApiController:list }
    methods: [POST, GET]